// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Zl1uZOvwnId4CrHcH9DR5XOfmsRJm8A',
    appId: '1:445354161677:web:f67a16b1a3e0f836568744',
    messagingSenderId: '445354161677',
    projectId: 'turneo-f9966',
    authDomain: 'turneo-f9966.firebaseapp.com',
    storageBucket: 'turneo-f9966.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRCCTi2FDALvTZOhA4-YXzVu1Hrd-cUQ',
    appId: '1:445354161677:android:5edf3c1a6ceccc9b568744',
    messagingSenderId: '445354161677',
    projectId: 'turneo-f9966',
    storageBucket: 'turneo-f9966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUuaAtF5kRtU5xzUJxyLchb9tKnDbnNU',
    appId: '1:445354161677:ios:6d3ab49ab0c1b847568744',
    messagingSenderId: '445354161677',
    projectId: 'turneo-f9966',
    storageBucket: 'turneo-f9966.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
